var INITIAL_POPULATION_SIZE = 5;
var INITIAL_GOAT_SPEED = 20; // Pixels per second
var INITIAL_GOAT_SIZE = 10;
var INITIAL_GOAT_FOOD = 100;

var NUMBER_CELLS_FACTOR = 4;
var GRID_THICKNESS = 0.3;

var TICK_TIME = 5000; // Milliseconds per tick